Wardrobe/Controllers/BottomsIDs1Controller.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Wardrobe.Models;

namespace Wardrobe.Controllers
{
    public class BottomsIDs1Controller : Controller
    {
        private WardrobeEntities db = new WardrobeEntities();

        // GET: BottomsIDs1
        public ActionResult Index()
        {
            return View(db.BottomsIDs.ToList());
        }

        // GET: BottomsIDs1/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BottomsID bottomsID = db.BottomsIDs.Find(id);
            if (bottomsID == null)
            {
                return HttpNotFound();
            }
            return View(bottomsID);
        }

        // GET: BottomsIDs1/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: BottomsIDs1/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "BottomsID1,BottomsName,BottomsPhoto,BottomsType,BottomsColor,BottomsSeason,BottomsOccasion")] BottomsID bottomsID)
        {
            if (ModelState.IsValid)
            {
                db.BottomsIDs.Add(bottomsID);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(bottomsID);
        }

        // GET: BottomsIDs1/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BottomsID bottomsID = db.BottomsIDs.Find(id);
            if (bottomsID == null)
            {
                return HttpNotFound();
            }
            return View(bottomsID);
        }

        // POST: BottomsIDs1/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "BottomsID1,BottomsName,BottomsPhoto,BottomsType,BottomsColor,BottomsSeason,BottomsOccasion")] BottomsID bottomsID)
        {
            if (ModelState.IsValid)
            {
                db.Entry(bottomsID).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(bottomsID);
        }

        // GET: BottomsIDs1/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            BottomsID bottomsID = db.BottomsIDs.Find(id);
            if (bottomsID == null)
            {
                return HttpNotFound();
            }
            return View(bottomsID);
        }

        // POST: BottomsIDs1/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            BottomsID bottomsID = db.BottomsIDs.Find(id);
            db.BottomsIDs.Remove(bottomsID);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Wardrobe/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet">
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Wardrobe", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Tops", "Index", "Tops")</li>
                    <li>@Html.ActionLink("Bottoms", "Index", "BottomsIDs1")</li>
                    <li>@Html.ActionLink("Shoes","Index", "Shoes")</li>
                    <li>@Html.ActionLink("Accessories", "Index", "Accessories")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>